spring:
  jpa:
    hibernate:
      ddl-auto: update
    naming:
      physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        format_sql: true
        show_sql: false
---
spring:
  config:
    activate:
      on-profile: local, test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace